<script setup lang="ts">
</script>

<template>
  <footer class="footer">
    <p>
      Generated by AI facilitated by leo
      <a href="https://github.com/leovoon/berapa" target="_blank" rel="noopener noreferrer" class="repo-link">
        @berapa
      </a>
    </p>
  </footer>
</template>

<style scoped>
.footer {
  margin-top: 2rem;
  padding: 1rem;
  text-align: center;
  color: #6b7280;
  font-size: 0.875rem;
}

.repo-link {
  color: #6b7280;
  text-decoration: none;
  transition: color 0.2s;
}

.repo-link:hover {
  color: #4b5563;
  text-decoration: underline;
}
</style>