<script setup lang="ts">
</script>

<template>
  <footer class="footer">
    <p>Generated by AI by leo</p>
  </footer>
</template>

<style scoped>
.footer {
  margin-top: 2rem;
  padding: 1rem;
  text-align: center;
  color: #6b7280;
  font-size: 0.875rem;
}
</style>